"use client";

import { type FormEvent, useEffect, useState } from "react";
import { apiPath } from "@/lib/client/url";

type Coach = { id:string; name:string; creator_name:string; coach_scope:"personal"|"platform"; status:"active"|"archived"; latest_version:number; identity_card:{title?:string;summary?:string}; sample_count:number; capabilities:string[]; source_count:number; change_summary:string; ip_positioning_prompt:string; content_creation_prompt:string; growth_prompt:string; content_skill_id:string|null; growth_skill_id:string|null };
type Attempt = { link?:string; title?:string; status?:string; stage?:string; message?:string };
type TrainingRun = { id:string; skill_name:string; training_purpose:"content"|"lead-coach"; status:"running"|"succeeded"|"failed"; phase:string; total_count:number; completed_count:number; successful_count:number; error_message:string; updated_at:string; queued_count:number; running_count:number; failed_count:number; attempts:Attempt[] };
type CoachTrainingJob = { id:string; coach_name:string; status:"waiting_source"|"queued"|"training"|"succeeded"|"failed"; phase:string; attempt_count:number; error_message:string; updated_at:string; source_run_id:string; source_status:string; source_total:number; source_completed:number; source_successful:number };
type WechatCandidate = { id:string; title:string; authorName:string; trainingToken:string };
const capabilityNames = ["IP定位","内容创作","获客增长"];

export function CreativeCoachProductionPanel() {
  const [tab,setTab]=useState<"library"|"submit"|"runs">("library");
  const [coaches,setCoaches]=useState<Coach[]>([]); const [runs,setRuns]=useState<TrainingRun[]>([]); const [jobs,setJobs]=useState<CoachTrainingJob[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [detailId,setDetailId]=useState(""); const [runDetailId,setRunDetailId]=useState("");
  const [submitting,setSubmitting]=useState(false); const [submitMessage,setSubmitMessage]=useState("");
  const [draft,setDraft]=useState({coachId:"",name:"",creatorName:"",links:"",authorized:false});
  const [channelId,setChannelId]=useState(""); const [previousChannelId,setPreviousChannelId]=useState("");
  const [candidates,setCandidates]=useState<WechatCandidate[]>([]); const [discovering,setDiscovering]=useState(false);
  useEffect(()=>{ const controller=new AbortController(); const load=()=>fetch(apiPath("/api/admin/creative-coaches"),{cache:"no-store",signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error||"读取教练失败");return payload as {coaches?:Coach[];runs?:TrainingRun[];jobs?:CoachTrainingJob[]};}).then(payload=>{setCoaches(payload.coaches??[]);setRuns(payload.runs??[]);setJobs(payload.jobs??[]);setError("");}).catch(cause=>{if(!(cause instanceof DOMException&&cause.name==="AbortError"))setError(cause instanceof Error?cause.message:"读取教练失败");}).finally(()=>setLoading(false)); void load(); const timer=window.setInterval(()=>void load(),15000); return()=>{window.clearInterval(timer);controller.abort();};},[]);
  async function discoverAccount(){if(!/^sph[A-Za-z0-9_-]+$/.test(channelId.trim())){setSubmitMessage("请输入有效的视频号 ID");return;}setDiscovering(true);setSubmitMessage("");try{const response=await fetch(apiPath("/api/avatar/wechat-channel/discover"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({channelId:channelId.trim(),previousChannelId:previousChannelId.trim()||undefined,limit:"all"})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"获取视频号作品失败");setCandidates(payload.candidates??[]);setSubmitMessage(`已获取 ${payload.candidates?.length??0} 条可训练作品，默认全部纳入训练。`);}catch(cause){setSubmitMessage(cause instanceof Error?cause.message:"获取视频号作品失败");}finally{setDiscovering(false);}}
  async function submitTraining(event:FormEvent){event.preventDefault();setSubmitMessage("");const links=[...new Set(draft.links.split(/[\s,，]+/).map(item=>item.trim()).filter(item=>/^https?:\/\//.test(item)))];const selected=coaches.find(coach=>coach.id===draft.coachId);const name=(selected?.name||draft.name).trim();const tokens=candidates.map(item=>item.trainingToken);if(!name||links.length+tokens.length<12||!draft.authorized){setSubmitMessage("请选择或填写教练、准备至少 12 条作品并确认授权。");return;}setSubmitting(true);try{const response=await fetch(apiPath("/api/admin/creative-coaches"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({coachId:selected?.id||undefined,name,creatorName:selected?.creator_name||draft.creatorName.trim(),links,wechatWorkTokens:tokens,authorized:true})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"训练任务提交失败");setSubmitMessage("最新版渐进训练已提交：素材解析完成后会自动训练三项能力、执行质量门并创建新版本。");setDraft(current=>({...current,links:"",authorized:false}));setCandidates([]);setTab("runs");}catch(cause){setSubmitMessage(cause instanceof Error?cause.message:"训练任务提交失败");}finally{setSubmitting(false);}}
  const legacyRuns=runs.filter(run=>!jobs.some(job=>job.source_run_id===run.id));
  const runningCount=jobs.filter(job=>!["succeeded","failed"].includes(job.status)).length+legacyRuns.filter(run=>run.status==="running").length;
  return <section className="adminAvatarProduction creativeCoachProduction">
    <div className="adminSectionTitle"><div><span>教练生产</span><h2>创作教练训练与版本管理</h2><p>一位教练统一承载 IP定位、内容创作和获客增长，训练结果与任务进度分别管理。</p></div></div>
    <nav className="creativeCoachTabs"><button className={tab==="library"?"active":""} onClick={()=>setTab("library")} type="button">教练库</button><button className={tab==="submit"?"active":""} onClick={()=>setTab("submit")} type="button">训练任务提交</button><button className={tab==="runs"?"active":""} onClick={()=>setTab("runs")} type="button">训练中的任务{runningCount?<em>{runningCount}</em>:null}</button></nav>
    {loading?<p className="adminEmptyHint">正在读取...</p>:error?<p className="adminEmptyHint">{error}</p>:null}
    {!loading&&!error&&tab==="library"?<div className="creativeCoachLibrary"><div className="creativeCoachLibraryHead"><div><span>教练库</span><strong>{coaches.length} 位创作教练</strong></div><small>点击教练可查看三项能力的完整训练结果。</small></div><div className="creativeCoachGrid">{coaches.map(coach=>{const card=coach.identity_card??{};return <article className={`creativeCoachAdminCard ${coach.status}`} key={coach.id}><header><div><span>{coach.coach_scope==="platform"?"平台教练":"个人教练"}</span><h3>{coach.name}</h3></div><em>{coach.status==="active"?"已上架":"未上架"}</em></header><strong>{card.title||"创作教练"}</strong><p>{card.summary||"由存量训练成果整合生成。"}</p><div className="creativeCoachCapabilityList">{capabilityNames.map(name=><span className={coach.capabilities.includes(name)?"ready":"missing"} key={name}>{coach.capabilities.includes(name)?"✓":"+"} {name}</span>)}</div><footer><span>V{coach.latest_version||1}</span><span>{coach.sample_count} 条样本</span><span>{coach.source_count} 个原分身</span></footer><button className="secondaryButton" onClick={()=>setDetailId(detailId===coach.id?"":coach.id)} type="button">{detailId===coach.id?"收起训练结果":"查看训练结果"}</button>{detailId===coach.id?<div className="creativeCoachResultDetail">{[["IP定位",coach.ip_positioning_prompt],["内容创作",coach.content_creation_prompt],["获客增长",coach.growth_prompt]].map(([name,prompt])=><section key={name}><strong>{name}</strong><pre>{prompt||"尚未训练该项能力"}</pre></section>)}</div>:null}</article>;})}</div></div>:null}
    {tab==="submit"?<form className="creativeCoachSubmit" onSubmit={submitTraining}><div><span>新建 / 继续训练</span><h3>提交创作教练素材</h3><p>统一使用最新版渐进训练：全量轻分析、覆盖性深训、分层 Skill、停止条件、质量门，再生成 IP定位、内容创作和获客增长三项能力。</p></div><label>训练对象<select value={draft.coachId} onChange={event=>setDraft(current=>({...current,coachId:event.target.value}))}><option value="">新建创作教练</option>{coaches.map(coach=><option key={coach.id} value={coach.id}>继续加训：{coach.name} · V{coach.latest_version}</option>)}</select></label>{!draft.coachId?<><label>教练名称<input value={draft.name} onChange={event=>setDraft(current=>({...current,name:event.target.value}))} placeholder="例如：林老师教练" /></label><label>创作者名称（可选）<input value={draft.creatorName} onChange={event=>setDraft(current=>({...current,creatorName:event.target.value}))} /></label></>:<p>新素材会按证据补丁更新该教练，不会直接覆盖旧版本。</p>}<fieldset className="wechatChannelPicker"><legend>通过视频号 ID 获取账号全部作品</legend><div className="wechatChannelDiscovery"><input value={channelId} onChange={event=>{setChannelId(event.target.value);setCandidates([]);}} placeholder="视频号 ID，例如 sph5bGYfAn6yQFY" /><button className="secondaryButton" disabled={discovering} onClick={()=>void discoverAccount()} type="button">{discovering?"正在获取...":"获取全部作品"}</button></div><input value={previousChannelId} onChange={event=>setPreviousChannelId(event.target.value)} placeholder="可填旧视频号 ID，复用历史作品缓存" />{candidates.length?<small>已获取 {candidates.length} 条作品，默认全部纳入本次训练。</small>:<small>系统会读取账号可训练作品并自动去重；最新版训练至少需要 12 条有效作品。</small>}</fieldset><label>授权作品链接<textarea value={draft.links} onChange={event=>setDraft(current=>({...current,links:event.target.value}))} placeholder="也可粘贴单条抖音、视频号或公众号链接，每行一条" /></label><p>本次共准备 {draft.links.split(/[\s,，]+/).filter(item=>/^https?:\/\//.test(item)).length+candidates.length} 条作品。</p><label className="avatarConsent"><input checked={draft.authorized} onChange={event=>setDraft(current=>({...current,authorized:event.target.checked}))} type="checkbox" />我确认拥有这些作品，或已获得用于 AI 训练的授权</label><button className="primaryButton" disabled={submitting} type="submit">{submitting?"正在提交...":draft.coachId?"继续加训并创建新版本":"开始完整训练"}</button>{submitMessage?<p>{submitMessage}</p>:null}</form>:null}
    {tab==="runs"?<div className="creativeCoachRuns"><div className="creativeCoachLibraryHead"><div><span>最新版训练任务</span><strong>{runningCount} 项进行中</strong></div><small>素材解析和渐进 Skill 训练每 15 秒自动续跑</small></div><div className="creativeCoachRunList">{jobs.map(job=>{const progress=job.source_total?Math.round(job.source_completed/job.source_total*100):0;const finished=job.status==="succeeded";return <article key={job.id}><header><div><strong>{job.coach_name}</strong><span>{formatCoachTrainingPhase(job.phase)}</span></div><em className={job.status}>{finished?"已完成":job.status==="failed"?"失败":"训练中"}</em></header><div className="creativeCoachRunProgress"><i style={{width:`${job.status==="training"?Math.max(progress,70):finished?100:progress}%`}} /></div><footer><span>素材 {job.source_completed}/{job.source_total}</span><span>有效 {job.source_successful}</span><span>渐进训练 {formatCoachTrainingPhase(job.phase)}</span><span>尝试 {job.attempt_count}</span><span>{new Date(job.updated_at).toLocaleString("zh-CN",{hour12:false})}</span></footer>{job.error_message?<p>{job.error_message}</p>:null}<button className="secondaryButton" onClick={()=>setRunDetailId(runDetailId===job.source_run_id?"":job.source_run_id)} type="button">{runDetailId===job.source_run_id?"收起素材明细":"查看素材明细"}</button>{runDetailId===job.source_run_id?<div className="creativeCoachAttemptList">{(runs.find(run=>run.id===job.source_run_id)?.attempts??[]).map((attempt,index)=><div key={`${attempt.link}-${index}`}><em className={attempt.status}>{attempt.status==="succeeded"?"成功":attempt.status==="failed"?"失败":attempt.status==="running"?"处理中":"排队"}</em><span>{attempt.title||attempt.link||`素材 ${index+1}`}</span><small>{attempt.message||attempt.stage}</small></div>)}</div>:null}</article>;})}{legacyRuns.map(run=>{const progress=run.total_count?Math.round(run.completed_count/run.total_count*100):0;return <article key={run.id}><header><div><strong>{run.skill_name}</strong><span>旧流程任务（仅保留进度）</span></div><em className={run.status}>{run.status==="running"?"处理中":run.status==="succeeded"?"已完成":"失败"}</em></header><div className="creativeCoachRunProgress"><i style={{width:`${progress}%`}} /></div><footer><span>{run.completed_count}/{run.total_count} · {progress}%</span><span>成功 {run.successful_count}</span><span>失败 {run.failed_count}</span><span>{new Date(run.updated_at).toLocaleString("zh-CN",{hour12:false})}</span></footer>{run.error_message?<p>{run.error_message}</p>:null}</article>;})}{!jobs.length&&!legacyRuns.length?<p className="adminEmptyHint">暂无教练训练任务。</p>:null}</div></div>:null}
  </section>;
}

function formatCoachTrainingPhase(phase:string){const labels:Record<string,string>={"waiting-source":"素材解析","source-failed":"素材失败","starting-progressive-training":"启动渐进训练","light-analysis":"全量轻分析","deep-analysis":"覆盖性深训","hierarchical-merge":"分层 Skill 合并","candidate-ready":"候选版本","quality-gate-passed":"质量门通过","quality-gate-failed":"质量门未通过",active:"已激活","waiting-retry":"等待续训",failed:"失败"};return labels[phase]||phase||"准备中";}
