"use client";
import { useRef, useState } from "react";
import { apiPath } from "@/lib/client/url";
import styles from "./spoken-video.module.css";
export type SpokenJob = {id:string;title:string;status:string;progress:number;error_message:string|null;video_url:string|null;preview_image_url:string|null;created_at:string;request_json?:{workflow?:string;production_mode?:"basic"|"smart";stage?:string;root_job_id?:string;base_version_id?:string;revision_number?:number;selected_version_id?:string;edit_instructions?:string;postproduction_revision?:string;material_plan?:Array<{id:string;visual:string;researchReferences?:Array<{title:string;url:string;kind:string;excerpt?:string;rights?:string}>;material:{source:string;title:string;license:string;licenseUrl?:string;credit?:string;changes?:string}}>}};
export const activeVideo=(job:SpokenJob)=>["queued","processing"].includes(job.status);
const versionNumber=(job:SpokenJob)=>job.request_json?.revision_number||1;
const stageLabels:Record<string,string>={queued:"等待制作",planning:"正在规划分镜",planning_revision:"正在整理修改要求",refining_visuals:"正在优化画面",heygen_submitting:"正在准备口播",heygen_rendering:"正在制作口播",presenter_ready:"口播已完成",researching:"正在准备画面素材",materials_ready:"画面准备就绪",composing:"正在剪辑画面",quality_check:"正在检查并完善成片",recovering:"正在恢复制作"};
export function SpokenVideoVersions({root,versions,available,onRefresh}:{root:SpokenJob;versions:SpokenJob[];available:boolean;onRefresh:()=>Promise<void>}){
  const [selected,setSelected]=useState("");const [instructions,setInstructions]=useState("");const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const lock=useRef(false);const requestKey=useRef<{text:string;base:string;id:string}|null>(null);const textRef=useRef<HTMLTextAreaElement>(null);
  const sorted=[...versions].sort((a,b)=>versionNumber(b)-versionNumber(a));
  const currentId=root.request_json?.selected_version_id||root.id;
  const chosen=versions.find(v=>v.id===(selected||currentId))||root;
  const preview=chosen.video_url?chosen:versions.find(v=>v.id===chosen.request_json?.base_version_id&&v.video_url)||sorted.find(v=>v.status==="completed"&&v.video_url);
  const running=sorted.find(activeVideo);const anyCompleted=versions.some(v=>v.status==="completed");
  async function submit(){
    const text=instructions.trim();if(lock.current||running)return;if(text.length<4){setError("请具体描述希望怎么修改");textRef.current?.focus();return;}
    if(!preview)return;lock.current=true;setBusy(true);setError("");setNotice("");
    if(requestKey.current?.text!==text||requestKey.current?.base!==preview.id)requestKey.current={text,base:preview.id,id:crypto.randomUUID()};
    try{const response=await fetch(apiPath(`/api/digital-human-videos/${preview.id}/versions`),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({instructions:text,requestId:requestKey.current.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||"修改提交失败");setSelected(data.job.id);setInstructions("");setEditing(false);setNotice("修改已提交。你可以继续观看已有版本，新版完成后会出现在这里。");requestKey.current=null;await onRefresh();}
    catch(e){setError(e instanceof Error?e.message:"提交失败，请重试");}finally{lock.current=false;setBusy(false);}
  }
  async function selectVersion(){if(!preview||busy)return;setBusy(true);setError("");try{const response=await fetch(apiPath(`/api/digital-human-videos/${root.id}/versions`),{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({versionId:preview.id})});const data=await response.json();if(!response.ok)throw new Error(data.error||"选择失败");await onRefresh();setNotice(`已选择 V${versionNumber(preview)} 作为当前版本`);}catch(e){setError(e instanceof Error?e.message:"选择失败");}finally{setBusy(false);}}
  return <article className={styles.workCard}>
    <header className={styles.workHeader}><div><h3>{root.title}</h3><p>{new Date(root.created_at).toLocaleDateString("zh-CN")} · {versions.length} 个版本{root.request_json?.production_mode?` · ${root.request_json.production_mode==="smart"?"智能版":"基础版"}`:""}</p></div><span className={`${styles.jobStatus} ${running?styles.working:anyCompleted?styles.success:styles.failed}`}>{running?"制作中":anyCompleted?"可预览":"未完成"}</span></header>
    <div className={styles.workBody}><div className={styles.previewPane}>
      {preview?.video_url?<video key={preview.id+preview.video_url} controls playsInline preload="metadata" poster={preview.preview_image_url||undefined} src={preview.video_url} aria-label={`${root.title} V${versionNumber(preview)}`}/>:<div className={styles.videoPlaceholder}><span>▷</span><p>{running?"你的作品正在制作中":"暂时没有可播放的视频"}</p><small>{running?"完成后即可预览和继续修改":"可以重新制作一条视频"}</small></div>}
      {preview?<div className={styles.previewActions}><span>正在预览 V{versionNumber(preview)}{preview.id===currentId?" · 当前版本":""}</span><a href={apiPath(`/api/digital-human-videos/${preview.id}/media?download=1`)}>下载此版本 ↓</a></div>:null}
      {preview?.request_json?.material_plan?.some(p=>p.material.source.includes("pexels.com")||p.material.source.includes("pixabay.com"))?<div className={styles.previewActions}><span>部分画面来自 {preview.request_json.material_plan.some(p=>p.material.source.includes("pexels.com"))?<a href="https://www.pexels.com/" target="_blank" rel="noreferrer">Pexels</a>:null}{preview.request_json.material_plan.some(p=>p.material.source.includes("pexels.com"))&&preview.request_json.material_plan.some(p=>p.material.source.includes("pixabay.com"))?"、":""}{preview.request_json.material_plan.some(p=>p.material.source.includes("pixabay.com"))?<a href="https://pixabay.com/" target="_blank" rel="noreferrer">Pixabay</a>:null}</span></div>:null}
    </div><div className={styles.versionPane}>
      <div className={styles.versionHeading}><h4>作品版本</h4><span>旧版始终保留</span></div>
      <div className={styles.versionList} role="group" aria-label={`${root.title}的版本`}>
        {sorted.map(v=><button key={v.id} type="button" className={`${styles.versionOption} ${chosen.id===v.id?styles.chosenVersion:""}`} aria-pressed={chosen.id===v.id} onClick={()=>{setSelected(v.id);setError("");setNotice("");}}><span><strong>V{versionNumber(v)}{v.id===root.id?" · 初版":""}</strong><small>{v.id===currentId?"当前版本":activeVideo(v)?"制作中":v.status==="failed"?"未完成":"可预览"}</small></span><p>{v.request_json?.edit_instructions||"首次生成的完整视频"}</p></button>)}
      </div>
      {running?<div className={styles.revisionProgress} role="status"><strong>{stageLabels[running.request_json?.stage||""]||"正在制作新版本"}</strong><div className={styles.progressRow}><progress aria-label="修改进度" value={running.progress||0} max={100}/><span>{running.progress||0}%</span></div><p>{preview?"当前播放的是已有版本，制作完成后可切换查看。":"你可以离开此页面，稍后回来查看。"}</p></div>:null}
      {chosen.status==="failed"?<div className={styles.revisionFailure} role="alert"><strong>这个版本未能完成</strong><p>{/^(仅支持|成片质检未通过|Codex 质检未通过)/.test(chosen.error_message||"")?chosen.error_message:preview?"已有成片已保留。请调整修改要求后重试，或稍后再试。":"生成未完成，请稍后重试。"}</p>{preview?<button type="button" onClick={()=>{setInstructions(chosen.request_json?.edit_instructions||"");setEditing(true);textRef.current?.focus();}}>重新修改</button>:null}</div>:null}
      {error?<p className={styles.error} role="alert">{error}</p>:null}{notice?<p className={styles.notice} role="status">{notice}</p>:null}
      {preview?<><div className={styles.versionActions}><button type="button" disabled={busy||Boolean(running)||!available} onClick={()=>{setEditing(!editing);setError("");}}>调整这个版本</button>{preview.id!==currentId?<button type="button" disabled={busy} onClick={()=>void selectVersion()}>设为当前版本</button>:null}</div>
      {editing?<div className={styles.editPanel}><label htmlFor={`edit-${root.id}`}>基于 V{versionNumber(preview)}，你想怎么调整？</label><textarea id={`edit-${root.id}`} ref={textRef} value={instructions} onChange={e=>setInstructions(e.target.value)} maxLength={1500} rows={4} disabled={busy||Boolean(running)} placeholder="例如：知识卡更精美，用暖色插画；字幕大一点，多展示知识点，减少全屏人物画面。"/><div className={styles.editChips}>{["知识卡更精美，使用有质感的插画","字幕大一点，保持透明背景","多展示知识点，减少全屏人物画面"].map(text=><button type="button" key={text} disabled={busy||Boolean(running)} onClick={()=>setInstructions(value=>value?`${value}；${text}`:text)}>{text}</button>)}</div><p>可调整素材、知识卡、字幕、标题和画面节奏。口播文案、人物和声音保持不变。</p><div className={styles.editFooter}><span>另存为新版本，保留已有视频</span><button type="button" disabled={busy||Boolean(running)||!available||instructions.trim().length<4} onClick={()=>void submit()}>{busy?"正在提交…":"生成修改版 →"}</button></div></div>:null}</>:null}
      {preview?.request_json?.material_plan?.some(p=>p.material.source.startsWith("https://"))?<details className={styles.sourceDetails}><summary>素材来源与署名</summary>{preview.request_json.material_plan.filter(p=>p.material.source.startsWith("https://")).map(p=><p key={p.id}><a href={p.material.source} target="_blank" rel="noreferrer">{p.material.title}</a>{p.material.credit?` · ${p.material.credit}`:""} · {p.material.licenseUrl?<a href={p.material.licenseUrl} target="_blank" rel="noreferrer">{p.material.license}</a>:p.material.license}{p.material.changes?` · ${p.material.changes}`:""}</p>)}</details>:null}
      {preview?.request_json?.material_plan?.some(p=>p.researchReferences?.length)?<details className={styles.sourceDetails}><summary>参考资料与画面线索</summary>{preview.request_json.material_plan.flatMap(p=>(p.researchReferences||[]).slice(0,3).map((source,index)=><p key={`${p.id}-${index}`}><strong>{p.visual}：</strong><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> · {source.kind==="document"?"文档":source.kind==="video"?"视频":source.kind==="image"?"图片":"网页"}{source.rights==="unverified"?" · 使用画面前需核对授权":""}</p>))}</details>:null}
    </div></div>
  </article>;
}
