import { randomUUID } from "node:crypto";
import sharp from "sharp";
import { query } from "@/lib/db/client";

export type AvatarContactQrCode = { id: string; label: string; qr_code_url: string; original_url: string; created_at: string };
export type AvatarContactCard = { display_name: string; organization: string; call_to_action: string; service_motto: string; phone: string; email: string; placement: "bottom-right" | "bottom-bar"; enabled_by_default: boolean; business_card_style: "classic" | "emerald" | "editorial" | "ivory" | "garden" | "lavender"; default_qr_code_id: string | null; qr_codes: AvatarContactQrCode[]; has_qr_code: boolean; qr_code_url: string | null; updated_at: string | null };
type CardRow = Omit<AvatarContactCard, "qr_codes" | "has_qr_code" | "qr_code_url">;

export async function getAvatarContactCard(userId: string): Promise<AvatarContactCard> {
  const [card, codes] = await Promise.all([query<CardRow>(`select display_name, organization, call_to_action, service_motto, phone, email, placement, enabled_by_default, business_card_style, default_qr_code_id, updated_at from avatar_contact_cards where user_id = $1`, [userId]), listAvatarContactQrCodes(userId)]);
  return toPublic(card.rows[0], codes);
}
export async function tryGetAvatarContactCard(userId: string): Promise<AvatarContactCard> { try { return await getAvatarContactCard(userId); } catch { return emptyAvatarContactCard(); } }
export async function listAvatarContactQrCodes(userId: string) { const result = await query<{ id: string; label: string; created_at: string }>(`select id, label, created_at from avatar_contact_qr_codes where user_id = $1 order by updated_at desc`, [userId]); return result.rows.map((row) => ({ ...row, qr_code_url: `/api/avatar/contact-card/content/${row.id}`, original_url: `/api/avatar/contact-card/content/${row.id}?original=1` })); }
export async function updateAvatarContactCard(userId: string, input: { display_name: string; organization: string; call_to_action: string; service_motto: string; phone: string; email: string; business_card_style: "classic" | "emerald" | "ivory" | "garden" | "lavender" | "editorial"; default_qr_code_id?: string | null }) {
  if (input.default_qr_code_id) { const found = await query(`select 1 from avatar_contact_qr_codes where id = $1 and user_id = $2`, [input.default_qr_code_id, userId]); if (!found.rows[0]) throw new Error("默认二维码不存在"); }
  const result = await query<CardRow>(`insert into avatar_contact_cards(user_id, display_name, organization, call_to_action, service_motto, phone, email, business_card_style, default_qr_code_id) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict (user_id) do update set display_name=excluded.display_name, organization=excluded.organization, call_to_action=excluded.call_to_action, service_motto=excluded.service_motto, phone=excluded.phone, email=excluded.email, business_card_style=excluded.business_card_style, default_qr_code_id=excluded.default_qr_code_id, updated_at=now() returning display_name, organization, call_to_action, service_motto, phone, email, placement, enabled_by_default, business_card_style, default_qr_code_id, updated_at`, [userId, input.display_name, input.organization, input.call_to_action, input.service_motto, input.phone, input.email, input.business_card_style, input.default_qr_code_id ?? null]);
  return toPublic(result.rows[0], await listAvatarContactQrCodes(userId));
}
export async function uploadAvatarContactQrCode(userId: string, fileName: string, contentType: string, bytes: Buffer) {
  if (!new Set(["image/jpeg", "image/png", "image/webp"]).has(contentType)) throw new Error("仅支持 JPG、PNG 或 WebP 格式的二维码"); if (!bytes.length || bytes.length > 8 * 1024 * 1024) throw new Error("二维码图片不能超过 8MB");
  const count = await query<{ count: string }>(`select count(*)::text as count from avatar_contact_qr_codes where user_id=$1`, [userId]); if (Number(count.rows[0]?.count ?? 0) >= 8) throw new Error("最多保存 8 个联系二维码");
  const image = await cropQrCode(bytes); const id = randomUUID();
  await query(`insert into avatar_contact_qr_codes(id, user_id, label, image_data, original_content_type, original_image_data) values ($1,$2,$3,$4,$5,$6)`, [id, userId, fileName.slice(0, 80), image, contentType, bytes]);
  await query(`insert into avatar_contact_cards(user_id, default_qr_code_id) values ($1,$2) on conflict (user_id) do update set default_qr_code_id = coalesce(avatar_contact_cards.default_qr_code_id, excluded.default_qr_code_id), updated_at=now()`, [userId, id]);
  return getAvatarContactCard(userId);
}
export async function deleteAvatarContactQrCode(userId: string, id: string) { const result = await query(`delete from avatar_contact_qr_codes where id=$1 and user_id=$2 returning id`, [id, userId]); if (!result.rows[0]) throw new Error("二维码不存在"); await query(`update avatar_contact_cards set default_qr_code_id=(select id from avatar_contact_qr_codes where user_id=$1 order by updated_at desc limit 1), updated_at=now() where user_id=$1 and default_qr_code_id is null`, [userId]); return getAvatarContactCard(userId); }
export async function readAvatarContactQrCode(userId: string, id?: string | null, original = false) { const result = await query<{ content_type: string; image_data: Buffer | null; original_content_type: string | null; original_image_data: Buffer | null }>(`select q.content_type, q.image_data, q.original_content_type, q.original_image_data from avatar_contact_qr_codes q left join avatar_contact_cards c on c.user_id=q.user_id where q.user_id=$1 and q.id=coalesce($2::uuid,c.default_qr_code_id) limit 1`, [userId, id ?? null]); const row = result.rows[0]; const bytes = original ? row?.original_image_data ?? row?.image_data : row?.image_data; return bytes?.length ? { content_type: original ? row?.original_content_type ?? row?.content_type ?? "image/png" : row?.content_type ?? "image/png", image_data: bytes } : null; }
function toPublic(row: CardRow | undefined, codes: AvatarContactQrCode[]): AvatarContactCard { const defaultId = row?.default_qr_code_id ?? codes[0]?.id ?? null; const selected = codes.find((item) => item.id === defaultId) ?? null; return { display_name: row?.display_name ?? "", organization: row?.organization ?? "", call_to_action: row?.call_to_action ?? "扫码联系我", service_motto: row?.service_motto ?? "保险不是推销，是长期的守护", phone: row?.phone ?? "", email: row?.email ?? "", placement: row?.placement ?? "bottom-right", enabled_by_default: row?.enabled_by_default ?? false, business_card_style: row?.business_card_style ?? "classic", default_qr_code_id: defaultId, qr_codes: codes, has_qr_code: Boolean(selected), qr_code_url: selected?.qr_code_url ?? null, updated_at: row?.updated_at ?? null }; }
function emptyAvatarContactCard(): AvatarContactCard { return { display_name: "", organization: "", call_to_action: "扫码联系我", service_motto: "保险不是推销，是长期的守护", phone: "", email: "", placement: "bottom-right", enabled_by_default: false, business_card_style: "classic", default_qr_code_id: null, qr_codes: [], has_qr_code: false, qr_code_url: null, updated_at: null }; }

async function cropQrCode(bytes: Buffer) {
  try { const image = sharp(bytes, { failOn: "error", limitInputPixels: 20_000_000 }).rotate(); const meta = await image.metadata(); const width = meta.width ?? 0, height = meta.height ?? 0; if (width < 180 || height < 180) throw new Error("二维码分辨率过低，请上传不小于 180 × 180px 的图片");
    return await image.resize({ width: 1200, height: 1200, fit: "inside", withoutEnlargement: true }).png().toBuffer();
  } catch (error) { throw error instanceof Error ? error : new Error("二维码图片无法识别"); }
}
