import{test}from'node:test';import assert from'node:assert/strict';import{mkdtemp,writeFile,readFile,rm,chmod}from'node:fs/promises';import os from'node:os';import path from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import http from'node:http';import sharp from'sharp';import{executeSpokenVideoProduction}from'./spoken-video-production.mjs';
const exec=promisify(execFile);
test('failed QA with no saved plan rebuilds only visuals and still requires the archived master',{timeout:30000},async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'failed-recut-'));let server;const previous=process.env.CODEX_CLI_BIN;
 try{
  const shim=path.join(dir,'test-codex');await writeFile(shim,`#!/usr/bin/env node\nconst fs=require('fs');if(fs.existsSync('recut-input.json')){const i=JSON.parse(fs.readFileSync('recut-input.json'));fs.writeFileSync('recut-plan.json',JSON.stringify({segments:i.segments.map(s=>({...s,regenerate:true})),options:{}}));}else{const i=JSON.parse(fs.readFileSync('research-input.json'));fs.writeFileSync('material-plan.json',JSON.stringify({segments:i.segments.map(s=>({...s,query:'cash flow',visual:'现金流'}))}));}\n`);await chmod(shim,0o700);process.env.CODEX_CLI_BIN=shim;
  const requests=[];server=http.createServer((req,res)=>{const kind=new URL(req.url,'http://test').searchParams.get('kind');requests.push(kind);if(kind==='recut'){res.setHeader('content-type','application/json');res.end(JSON.stringify({title:'现金流',script:'家庭现金流需要结合支出和收入判断。',aspectRatio:'9:16',productionMode:'smart',baseProductionMode:'smart',materialPlan:null,instructions:'重新混剪图解',options:{}}));}else{res.writeHead(404);res.end('missing master');}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  await assert.rejects(executeSpokenVideoProduction({payload:{mode:'recut',jobId:'fixture'}},'lease',{remoteBase:`http://127.0.0.1:${server.address().port}`,token:'test',updateDigitalHumanProgress:async()=>{},publishTaskEvent:async()=>{}}));
  assert.deepEqual(requests,['recut','master']);
 }finally{if(server)await new Promise(resolve=>server.close(resolve));if(previous===undefined)delete process.env.CODEX_CLI_BIN;else process.env.CODEX_CLI_BIN=previous;await rm(dir,{recursive:true,force:true});}
});
test('real FFmpeg recut reuses archived master and visuals without calling a generation provider',{timeout:120000},async()=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'recut-regression-'));let server;const previous=process.env.CODEX_CLI_BIN;
 try{
  const master=path.join(dir,'master.mp4');await exec('ffmpeg',['-v','error','-y','-f','lavfi','-i','color=c=teal:s=360x640:r=30','-f','lavfi','-i','anullsrc=r=44100:cl=stereo','-t','6','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-c:a','aac',master]);
  const media=await readFile(master),picture=await sharp({create:{width:1080,height:1920,channels:3,background:'#edf2ef'}}).jpeg().toBuffer();
  const shim=path.join(dir,'test-codex');await writeFile(shim,`#!/usr/bin/env node\nconst fs=require('fs');const a=process.argv.slice(2);if(a.includes('-o'))fs.writeFileSync(a[a.indexOf('-o')+1],JSON.stringify({pass:true,issues:[]}));else{const i=JSON.parse(fs.readFileSync('recut-input.json'));fs.writeFileSync('recut-plan.json',JSON.stringify({segments:i.segments.map(s=>({...s,regenerate:false})),options:{presenterShare:.4,subtitleFontSize:14}}));}\n`);await chmod(shim,0o700);process.env.CODEX_CLI_BIN=shim;
  const requests=[],uploads=new Map();const segment={id:'s1',text:'家里有没有足够现金？',visual:'现金流安全',material:{mediaId:'existing-image',kind:'image',title:'现金流安全',source:'xiaogu-ai-knowledge-card',license:'generated'}};
  server=http.createServer(async(req,res)=>{requests.push(req.method+' '+req.url);const url=new URL(req.url,'http://test');if(req.method==='PUT'){const chunks=[];for await(const chunk of req)chunks.push(chunk);const data=Buffer.concat(chunks);uploads.set(url.searchParams.get('kind'),data);res.setHeader('content-type','application/json');res.end(JSON.stringify({url:'/api/digital-human-media/fixture-'+url.searchParams.get('kind'),size:data.length}));return;}
   const kind=url.searchParams.get('kind');if(kind==='recut'){res.setHeader('content-type','application/json');res.end(JSON.stringify({title:'现金流',script:segment.text,aspectRatio:'9:16',subtitleSrt:'1\n00:00:00,000 --> 00:00:06,000\n家里有没有足够现金？\n',materialPlan:[segment],options:{},instructions:'字幕大一点'}));}else if(kind==='master'){res.setHeader('content-type','video/mp4');res.end(media)}else if(kind==='material'){res.setHeader('content-type','image/jpeg');res.end(picture)}else{res.writeHead(500);res.end('Unexpected provider call');}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const updates=[];
  const result=await executeSpokenVideoProduction({payload:{mode:'recut',jobId:'fixture'}},'lease',{remoteBase:`http://127.0.0.1:${server.address().port}`,token:'test',updateDigitalHumanProgress:async(_id,v)=>updates.push(v),publishTaskEvent:async()=>{}});
  assert.equal(result.status,'completed');assert.ok(Math.abs(result.durationSeconds-6)<.3);assert.equal(result.materialPlan[0].material.mediaId,'existing-image');assert.equal(result.editOptions.subtitleFontSize,14);assert.ok(uploads.get('output')?.length>20000);assert.ok(uploads.get('cover')?.length>1000);assert.equal(uploads.has('presenter_master'),false);assert.equal(uploads.has('material'),false);assert.equal(requests.some(r=>r.includes('/visual')),false);assert.ok(updates.some(v=>v.stage==='planning_revision'));assert.deepEqual(await readFile(master),media);
  const exported=path.join(dir,'exported.mp4');await writeFile(exported,uploads.get('output'));
  const decoded=await exec('ffmpeg',['-hide_banner','-i',exported,'-f','null','-']);
  assert.match(decoded.stderr,/Video: h264/);assert.match(decoded.stderr,/Audio: aac/);
  const frame=await exec('ffmpeg',['-v','error','-ss','1','-i',exported,'-frames:v','1','-f','image2pipe','-vcodec','png','-'],{encoding:'buffer',maxBuffer:8*1024*1024});
  const pixels=await sharp(frame.stdout).stats();assert.ok(pixels.channels.some(channel=>channel.stdev>10),'rendered frame contains visible title/subtitle content');
 }finally{if(server)await new Promise(resolve=>server.close(resolve));if(previous===undefined)delete process.env.CODEX_CLI_BIN;else process.env.CODEX_CLI_BIN=previous;await rm(dir,{recursive:true,force:true});}
});
