import test from 'node:test';import assert from 'node:assert/strict';import{createServer}from'node:http';import{createHash}from'node:crypto';import{mkdtemp,readFile,rm,writeFile}from'node:fs/promises';import os from'node:os';import path from'node:path';import{downloadPresenterMaster}from'./spoken-video-master-download.mjs';
const bytes=Buffer.from('0123456789abcdef'.repeat(2048));
async function fixture(work){const dir=await mkdtemp(path.join(os.tmpdir(),'master-download-'));try{await work({dir,identity:{id:'11111111-1111-4111-8111-111111111111',size:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')}});}finally{await rm(dir,{recursive:true,force:true});}}
async function server(handler,work){const s=createServer(handler);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await work('http://127.0.0.1:'+s.address().port+'/master');}finally{s.closeAllConnections();await new Promise(r=>s.close(r));}}
const response=(res,start,end)=>{res.writeHead(206,{'content-range':`bytes ${start}-${end}/${bytes.length}`,'content-length':end-start+1});};
test('slow stream continues beyond idle interval while data arrives; cache verifies bytes and avoids download',()=>fixture(async({dir,identity})=>{let calls=0;await server((req,res)=>{calls++;let [start,end]=req.headers.range.slice(6).split('-').map(Number);response(res,start,end);const step=512;const timer=setInterval(()=>{if(res.destroyed){clearInterval(timer);return;}const next=Math.min(start+step,end+1);res.write(bytes.subarray(start,next));start=next;if(start>end){clearInterval(timer);res.end();}},10);},async url=>{const opts={url,identity,cacheDir:dir,file:path.join(dir,'output'),idleMs:150,totalMs:5000,partBytes:bytes.length};await downloadPresenterMaster(opts);assert.deepEqual(await readFile(opts.file),bytes);assert.equal((await downloadPresenterMaster(opts)).cacheHit,true);assert.equal(calls,1);});}));
test('interrupted body resumes at persisted offset, including a later invocation',()=>fixture(async({dir,identity})=>{let first=true;const starts=[];await server((req,res)=>{const[start,end]=req.headers.range.slice(6).split('-').map(Number);starts.push(start);response(res,start,end);if(first){first=false;res.write(bytes.subarray(start,start+1024));setTimeout(()=>res.destroy(),30);}else res.end(bytes.subarray(start,end+1));},async url=>{const opts={url,identity,cacheDir:dir,file:path.join(dir,'output'),partBytes:4096,attempts:1,sleep:async()=>{}};await assert.rejects(downloadPresenterMaster(opts),/已保留 1024/);const r=await downloadPresenterMaster(opts);assert.equal(r.resumedBytes,1024);assert.equal(starts[1],1024);assert.deepEqual(await readFile(opts.file),bytes);});}));
test('ignoring Range or wrong checksum is rejected; cached corruption cannot silently pass',()=>fixture(async({dir,identity})=>{await server((req,res)=>{res.writeHead(200,{'content-length':bytes.length});res.end(bytes);},async url=>{await assert.rejects(downloadPresenterMaster({url,identity,cacheDir:dir,file:path.join(dir,'out'),attempts:1}),/续传响应无效/);});await server((req,res)=>{const[start,end]=req.headers.range.slice(6).split('-').map(Number);response(res,start,end);res.end(Buffer.alloc(end-start+1,42));},async url=>{await assert.rejects(downloadPresenterMaster({url,identity,cacheDir:dir,file:path.join(dir,'out'),partBytes:bytes.length}),/SHA-256/);});}));
test('idle transfer fails within bound and permanent authorization error does not retry',()=>fixture(async({dir,identity})=>{for(const denied of [false,true]){let calls=0;await server((req,res)=>{calls++;if(denied){res.writeHead(403);res.end();}},async url=>{const before=Date.now();await assert.rejects(downloadPresenterMaster({url,identity,cacheDir:dir,file:path.join(dir,'out'),idleMs:50,totalMs:300,attempts:2,sleep:async()=>{}}));assert(Date.now()-before<2000);assert.equal(calls,denied?1:2);});}}));
