import type { AcceptanceCase } from "./acceptance-harness.ts";

export const WORKBUDDY_FUSION_CASES:AcceptanceCase[]=[
  {id:"hotspot-fast-research",title:"热点发现后只核验入选对象",tags:["research","fusion"],expect:{capabilityId:"agent.fast-research",operation:"verify",invocationCount:1,maxIterations:3,maxPoints:5}},
  {id:"research-to-traffic-copy",title:"研究成果进入流量口播",tags:["research","text","fusion"],expect:{capabilityId:"app.traffic-copy",operation:"create",maxIterations:4,maxPoints:5,requiredSourceFragments:["已核验事实"],forbiddenSourceFragments:["结合已取得的研究观察，执行用户要求的专业产物"]}},
  {id:"two-topics-two-scripts",title:"两个选题分别生成两篇口播",tags:["text","multi-output","fusion"],expect:{capabilityId:"app.traffic-copy",operation:"create",invocationCount:1,maxIterations:3,maxPoints:5,outputKind:"text",outputCount:2,outputSlots:["text:1","text:2"]}},
  {id:"scripts-to-video-covers",title:"两篇口播分别生成两张视频封面",tags:["image","multi-output","fusion"],expect:{capabilityId:"app.video-cover",operation:"transform",invocationCount:1,maxIterations:3,maxPoints:5,requiredSourceFragments:["第一篇真实正文","第二篇真实正文"],outputKind:"image",outputCount:2,outputSlots:["image:1","image:2"],requireDownloads:true}},
  {id:"articles-to-knowledge-cards",title:"两篇内容分别生成知识卡片",tags:["image","multi-output","fusion"],expect:{capabilityId:"app.image-card",operation:"transform",invocationCount:1,maxIterations:3,maxPoints:5,outputKind:"image",outputCount:2,outputSlots:["image:1","image:2"],requireDownloads:true}},
  {id:"wechat-to-images",title:"公众号文章进入多配图应用",tags:["wechat","image","fusion"],expect:{capabilityId:"app.wechat-images",operation:"transform",invocationCount:1,maxIterations:3,requiredSourceFragments:["公众号正文"],outputKind:"image",outputCount:4,requireDownloads:true}},
  {id:"script-to-digital-human",title:"选定口播带入数字人工作台",tags:["video","fusion","human-in-loop"],expect:{capabilityId:"app.digital-human-video",operation:"transform",invocationCount:1,maxIterations:3,requiredSourceFragments:["选定口播正文"],outputKind:"data",outputCount:1}},
  {id:"video-to-openchatcut",title:"数字人视频进入可编辑时间线",tags:["video","external-write","fusion"],expect:{capabilityId:"mcp.openchatcut",operation:"transform",invocationCount:1,maxIterations:3,requiredSourceFragments:["视频素材地址"],outputCount:1}},
  {id:"file-to-ppt",title:"文件分析成果进入 PPT",tags:["file","presentation","fusion"],expect:{capabilityId:"app.ppt-maker",operation:"transform",invocationCount:1,maxIterations:3,requiredSourceFragments:["结构化结论"],outputKind:"presentation",outputCount:1,requireDownloads:true}},
  {id:"research-to-wechat",title:"研究证据进入公众号文章",tags:["research","wechat","fusion"],expect:{capabilityId:"app.wechat-studio",operation:"create",invocationCount:1,maxIterations:3,requiredSourceFragments:["来源：https://"],outputKind:"text",outputCount:1}},
  {id:"draft-to-polish",title:"已有正文进入定向润色",tags:["edit","fusion"],expect:{capabilityId:"app.video-script-polish",operation:"revise",invocationCount:1,maxIterations:3,requiredSourceFragments:["已有完整正文"],outputKind:"text",outputCount:1}},
  {id:"link-to-remix",title:"链接解析结果进入二创",tags:["link","fusion"],expect:{capabilityId:"app.link-remix",operation:"transform",invocationCount:1,maxIterations:4,requiredSourceFragments:["原作者","原始链接","原文内容"],outputKind:"text",outputCount:1}},
  {id:"partial-image-repair",title:"两张图片一张失败时只补缺失槽",tags:["repair","image","fusion"],expect:{capabilityId:"app.image-card",operation:"transform",invocationCount:2,maxIterations:4,maxPoints:5,outputKind:"image",outputCount:2,outputSlots:["image:1","image:2"],requireDownloads:true}},
  {id:"duplicate-confirmation",title:"重复确认不重复调用和扣费",tags:["idempotency","billing"],expect:{capabilityId:"app.video-cover",operation:"transform",invocationCount:1,maxIterations:2,maxPoints:5,outputKind:"image",outputCount:1}},
  {id:"topic-switch",title:"切换新主题后不携带旧成果",tags:["context","fusion"],expect:{capabilityId:"agent.fast-research",operation:"research",invocationCount:1,maxIterations:3,forbiddenSourceFragments:["旧主题素材"]}},
  {id:"explicit-skill-overrides-semantic-routing",title:"显式选择 Skill 后不被语义路由改选",tags:["routing","explicit-selection","fusion"],expect:{capabilityId:"app.digital-human-video",operation:"create",invocationCount:1,maxIterations:2,requiredSourceFragments:["用户真实口播正文"],outputKind:"data",outputCount:1}},
  {id:"cancel-propagates-before-billing",title:"停止任务传播到应用运行且不扣费",tags:["cancellation","billing","fusion"],expect:{capabilityId:"app.video-script-polish",operation:"revise",invocationCount:1,maxIterations:2,maxPoints:5,requiredSourceFragments:["真实待处理素材"]}},
  {id:"queued-explicit-skill-starts-fresh-turn",title:"执行中选择新应用后以独立新轮处理素材",tags:["queue","routing","explicit-selection","context","fusion"],expect:{capabilityId:"app.image-card",operation:"transform",invocationCount:1,maxIterations:3,maxPoints:5,requiredSourceFragments:["第一篇真实正文","第二篇真实正文"],forbiddenSourceFragments:["上一应用输出契约"],outputKind:"image",outputCount:2,outputSlots:["image:1","image:2"],requireDownloads:true}},
];

export const REQUIRED_FUSION_TAGS=["research","text","image","video","presentation","file","link","edit","repair","idempotency","billing","context","external-write","routing","explicit-selection","cancellation","queue"];
