import { z } from "zod";
import { requireSessionUser } from "@/lib/auth/session";
import { deleteAvatarContactQrCode, getAvatarContactCard, updateAvatarContactCard, uploadAvatarContactQrCode } from "@/lib/avatar/contact-card";

export const runtime = "nodejs";
const settingsSchema = z.object({ displayName: z.string().trim().max(40), organization: z.string().trim().max(60), callToAction: z.string().trim().min(1).max(50), serviceMotto: z.string().trim().max(60), phone: z.string().trim().max(30), email: z.string().trim().max(120).refine((value) => !value || z.email().safeParse(value).success, "邮箱格式不正确"), businessCardStyle: z.enum(["classic", "emerald", "editorial", "ivory", "garden", "lavender"]), defaultQrCodeId: z.string().uuid().nullable().optional() });

export async function GET() { const user = await requireSessionUser(); if (user instanceof Response) return user; return Response.json({ contactCard: await getAvatarContactCard(user.id) }); }
export async function PUT(request: Request) { const user = await requireSessionUser(); if (user instanceof Response) return user; const parsed = settingsSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return Response.json({ error: parsed.error.issues[0]?.message ?? "联系名片信息不完整" }, { status: 400 }); const value = parsed.data; try { return Response.json({ contactCard: await updateAvatarContactCard(user.id, { display_name: value.displayName, organization: value.organization, call_to_action: value.callToAction, service_motto: value.serviceMotto, phone: value.phone, email: value.email, business_card_style: value.businessCardStyle, default_qr_code_id: value.defaultQrCodeId }) }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "联系名片保存失败" }, { status: 400 }); } }
export async function POST(request: Request) { const user = await requireSessionUser(); if (user instanceof Response) return user; const form = await request.formData().catch(() => null); const file = form?.get("file"); if (!(file instanceof File)) return Response.json({ error: "请选择二维码图片" }, { status: 400 }); try { return Response.json({ contactCard: await uploadAvatarContactQrCode(user.id, file.name, file.type, Buffer.from(await file.arrayBuffer())) }, { status: 201 }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "二维码上传失败" }, { status: 400 }); } }
export async function DELETE(request: Request) { const user = await requireSessionUser(); if (user instanceof Response) return user; const id = new URL(request.url).searchParams.get("id"); if (!id || !z.string().uuid().safeParse(id).success) return Response.json({ error: "二维码参数不正确" }, { status: 400 }); try { return Response.json({ contactCard: await deleteAvatarContactQrCode(user.id, id) }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "二维码删除失败" }, { status: 400 }); } }
