import type { CreationExample } from "./catalog";

export const creationExamples: CreationExample[] = [
  {
    slug: "multi-channel-family-review",
    appSlug: "write-copy",
    title: "一次家庭保障复盘，拆成四个平台内容",
    summary: "展示同一条专业观点如何针对不同平台调整长度、节奏和互动方式。",
    intro: "素材来自一次匿名化的家庭保障复盘：先梳理责任，再讨论是否需要补充，而不是从产品开始。",
    highlight: "观点保持一致，表达随渠道变化；不编造客户经历和产品结论。",
    ctaLabel: "用我的素材创作",
    sections: [
      { title: "核心判断", body: "家庭保障不是险种清单，而是收入中断、医疗支出和长期照护三类风险的应对顺序。" },
      { title: "表达边界", body: "不承诺理赔，不使用未经核验的产品数据，不把个案写成普遍结论。" },
    ],
    outputs: [
      { title: "短视频口播", tag: "60 秒", body: "很多家庭复盘保单时，第一反应是问还缺哪一种保险。\n\n我更建议先换一个顺序：如果收入突然停下来，哪些支出最先受到影响？如果遇到大额医疗费用，现金流能撑多久？需要长期照护时，谁来承担时间和费用？\n\n先把问题排清楚，再看现有保障分别解决了什么。这样做的目的不是多买，而是让每一笔预算都有明确任务。" },
      { title: "朋友圈", body: "保障复盘最重要的不是数保单，而是确认三件事：收入中断谁来托住、医疗支出怎么承接、长期照护由谁承担。先看风险顺序，再谈产品。" },
      { title: "公众号开篇", viewMode: "wechat", body: "一份看起来很完整的保单清单，未必能回答家庭真正担心的问题。保障规划的起点，应当是家庭现金流和责任，而不是产品数量。" },
    ],
  },
  {
    slug: "knowledge-card-path",
    appSlug: "image-card",
    title: "家庭保障复盘路径图",
    summary: "把抽象的保障复盘方法整理成一张可阅读、可保存的知识卡片。",
    intro: "卡片只呈现方法框架，不展示虚构收益、保额或客户数据。",
    exampleType: "image",
    sections: [],
    imageResults: [
      { title: "路径卡片", imageUrl: "/examples/image-card-styles/flat-knowledge.webp", badge: "原创示例", ratio: "3 / 4", prompt: "保险内容知识卡片，展示定位、内容、信任、转化、复盘五步路径，清晰留白，中文可读。" },
    ],
  },
  {
    slug: "consultation-checklist-lead",
    appSlug: "lead-copy",
    title: "家庭保障沟通清单引流示例",
    summary: "用实用清单承接评论和私信，不通过焦虑或夸大风险吸引用户。",
    intro: "先交付可验证的价值，再给出清晰、克制的领取动作。",
    sections: [{ title: "转化路径", body: "具体问题切入 -> 给出一条可用建议 -> 说明清单内容 -> 邀请自愿领取。" }],
    outputs: [
      { title: "口播结尾", body: "如果你也准备整理家庭保障，可以先把收入责任、医疗预算和长期照护这三栏写下来。我做了一份空白沟通清单，需要的话评论“清单”，我发给你自行填写。" },
      { title: "私信首句", body: "这是你领取的家庭保障沟通清单。建议先独立填写；涉及具体条款时，以合同和保险公司正式说明为准。" },
    ],
  },
  {
    slug: "family-risk-workbook",
    appSlug: "lead-package",
    title: "家庭风险沟通工作簿",
    summary: "从资料定位、目录到领取说明，组成一份完整但不过度营销的交付方案。",
    intro: "资料帮助用户整理问题，不替代正式保险建议。",
    sections: [
      { title: "目录", body: "1. 家庭责任地图\n2. 固定支出清单\n3. 医疗与照护情景\n4. 现有保障记录\n5. 待核实问题" },
      { title: "使用说明", body: "先自行填写事实，再带着问题咨询专业人员；产品责任以正式合同为准。" },
    ],
    outputs: [{ title: "领取文案", body: "回复“工作簿”领取空白版。资料不含产品推荐，适合先把家庭情况和问题整理清楚。" }],
  },
  {
    slug: "topic-matrix-30-days",
    appSlug: "topic-picker",
    title: "30 天内容主题矩阵",
    summary: "按照触达、解释、信任三个目标设计选题，避免只追逐热点。",
    intro: "选题从真实客户问题和公开信息出发，每条都标注核验要求。",
    sections: [
      { title: "触达主题", body: "为什么保单数量不等于保障完整？\n家庭固定支出里，哪几项最怕收入中断？" },
      { title: "解释主题", body: "免赔额应该怎么读？\n等待期、犹豫期和宽限期分别解决什么问题？" },
      { title: "信任主题", body: "做保障复盘时，我为什么先问家庭责任？\n遇到不确定条款时，如何完成三步核验？" },
    ],
    outputs: [{ title: "本周执行建议", body: "先发布一条真实问题拆解，再发布一条术语解释，第三条用工作方法建立信任。所有事实在发布前核对来源和日期。" }],
  },
  {
    slug: "advisor-positioning-map",
    appSlug: "ip-positioning",
    title: "理性家庭规划者定位图",
    summary: "从服务对象、可信证据和内容边界形成可执行的个人定位。",
    intro: "定位来自用户真实经历和能力，不包装不存在的资历。",
    sections: [
      { title: "一句话定位", body: "帮助双职工家庭把复杂保障问题整理成能讨论、能核验、能执行的决策清单。" },
      { title: "内容支柱", body: "家庭责任、医疗费用、长期照护、合同阅读、沟通方法。" },
    ],
    outputs: [{ title: "主页简介", body: "关注家庭风险沟通与保障复盘。把复杂条款讲清楚，把重要问题列出来。具体责任以合同为准。" }],
  },
  {
    slug: "content-restart-plan",
    appSlug: "breakthrough",
    title: "停更后的四周重启计划",
    summary: "围绕低反馈和难坚持的问题，给出可量化的内容恢复节奏。",
    intro: "目标不是短期爆款，而是恢复稳定生产和有效对话。",
    sections: [
      { title: "问题诊断", body: "选题过大、每篇制作成本过高、缺少固定复盘指标。" },
      { title: "四周动作", body: "第一周收集 20 个真实问题；第二周发布 3 条短内容；第三周形成一个系列；第四周复盘收藏、私信问题和完读率。" },
    ],
    outputs: [{ title: "复盘指标", body: "记录有效提问数、收藏率、完读率和可复用素材数，不以单条播放量判断全部效果。" }],
  },
  {
    slug: "team-day-story",
    appSlug: "team-recruit",
    title: "团队真实工作日招募内容",
    summary: "用工作方式、培养机制和适配条件说明团队，而不是承诺收入。",
    intro: "所有数据、荣誉和成员故事必须取得授权并可核验。",
    sections: [{ title: "内容结构", body: "一天做什么 -> 新人如何学习 -> 团队如何复盘 -> 哪些人并不适合 -> 自愿咨询入口。" }],
    outputs: [{ title: "招募短文", body: "我们更看重持续学习、认真记录和愿意复盘。加入前会把日常工作、培养方式和考核要求讲清楚，不用模糊的高收入承诺吸引人。" }],
  },
  {
    slug: "medical-cost-live",
    appSlug: "live-script",
    title: "读懂医疗费用清单直播提纲",
    summary: "用问题驱动的直播结构解释基础概念，并设置事实核验节点。",
    intro: "直播不提供个案诊断，涉及产品时回到正式条款。",
    sections: [
      { title: "流程", body: "开场问题 3 分钟；费用清单拆解 12 分钟；常见误区 10 分钟；观众问答 10 分钟；核验提醒与收尾 5 分钟。" },
      { title: "互动问题", body: "你最看不懂费用清单里的哪一栏？先收集问题，再按概念分类解释。" },
    ],
    outputs: [{ title: "开场", body: "今天不讲某个产品值不值得买，我们只解决一个更基础的问题：拿到医疗费用清单时，应该先看哪几栏？" }],
  },
  {
    slug: "retirement-public-topic",
    appSlug: "general-content",
    title: "从延迟退休讨论到家庭时间预算",
    summary: "将公共话题转成生活决策内容，不借热点制造恐慌。",
    intro: "先确认政策信息和发布日期，再区分事实、推测和个人观点。",
    sections: [{ title: "深层问题", body: "公共讨论背后，是家庭如何安排工作年限、照护责任和可支配时间。" }],
    outputs: [{ title: "口播开篇", body: "讨论退休年龄时，我们常盯着一个数字。对普通家庭来说，更值得提前算的其实是三张时间表：工作、照护和自己的生活。" }],
  },
  {
    slug: "article-image-rhythm",
    appSlug: "wechat-images",
    title: "长文阅读节奏配图组",
    summary: "用四张视觉分工不同的图片支撑开篇、方法、转折和总结。",
    intro: "图片不复制文章全文，只承担章节定位和阅读停顿。",
    exampleType: "image",
    sections: [],
    imageResults: [
      { title: "开篇", imageUrl: "/examples/image-card-styles/magazine.webp", badge: "4 张原创示例", ratio: "3 / 4" },
      { title: "方法", imageUrl: "/examples/image-card-styles/line-illustration.webp", ratio: "3 / 4" },
      { title: "转折", imageUrl: "/examples/image-card-styles/morandi.webp", ratio: "3 / 4" },
      { title: "总结", imageUrl: "/examples/image-card-styles/white-orange-blue.webp", ratio: "3 / 4" },
    ],
  },
  {
    slug: "spoken-script-review",
    appSlug: "video-script-polish",
    title: "把术语堆叠改成可听懂的口播",
    summary: "通过删减、换序和口语化，让专业内容能直接说出口。",
    intro: "精修保留原观点，不新增未经核验的事实。",
    sections: [
      { title: "主要问题", body: "开头没有问题意识；连续出现多个术语；结尾缺少明确的小结。" },
      { title: "修改策略", body: "先抛真实问题，再一次解释一个概念，最后给出核验动作。" },
    ],
    outputs: [{ title: "精修片段", body: "看医疗险条款时，先别急着比较一长串责任。第一步只确认：哪些费用在范围内，哪些情况明确不在。把边界看懂，再谈额度。" }],
  },
  {
    slug: "anniversary-letter",
    appSlug: "letter",
    title: "写给长期读者的一封周年信",
    summary: "以真实进展、感谢和下一步计划组成一封克制的长信。",
    intro: "不编造用户数量、成交数据或客户评价。",
    sections: [{ title: "情绪路径", body: "具体回忆 -> 承认不足 -> 感谢陪伴 -> 说明下一步 -> 真诚祝福。" }],
    outputs: [{ title: "正文节选", body: "这一年，我最珍惜的不是发布了多少内容，而是一些问题被认真问出来，也被认真回答。谢谢你愿意把时间留给这些并不轻松的话题。下一年，我会继续把复杂的事讲清楚，也会更诚实地标出不知道和需要核验的地方。" }],
  },
  {
    slug: "platform-copy-check",
    appSlug: "xiaohongshu-check",
    title: "一条保险科普笔记的发布前检查",
    summary: "识别绝对化、收益暗示、焦虑营销和缺少依据的数字。",
    intro: "检测结果用于辅助复核，不代表平台官方审核结论。",
    sections: [{ title: "检查项", body: "事实来源、绝对化用语、收益与理赔承诺、个案泛化、敏感个人信息、互动诱导。" }],
    outputs: [{ title: "改写建议", body: "把“肯定能赔”改为对适用责任和限制条件的客观说明，并提醒读者以合同及保险公司审核结果为准。" }],
  },
  {
    slug: "policy-structure-review",
    appSlug: "policy-diagnosis",
    title: "现有保单信息结构化复核",
    summary: "整理责任、期限、保额和待确认问题，不自动给出购买结论。",
    intro: "示例只展示信息整理方法，不构成保险建议。",
    sections: [{ title: "复核维度", body: "投保人与被保险人、保障期间、责任范围、除外责任、等待期、续保条件、保费变化、信息缺口。" }],
    outputs: [{ title: "待确认问题", body: "当前资料未包含完整除外责任和续保说明。请补充正式合同对应页面，或向保险公司核实后再判断。" }],
  },
  {
    slug: "wechat-article-clarity",
    appSlug: "wechat-article-polish",
    title: "把一篇保险科普长文改得更清楚",
    summary: "在不改变事实和立场的前提下，优化标题、层级、段落和结尾。",
    intro: "精修过程标明事实缺口，不用流畅表达掩盖不确定性。",
    sections: [{ title: "优化重点", body: "标题具体；每节只回答一个问题；术语首次出现即解释；结尾给出核验路径。" }],
    outputs: [{ title: "精修开篇", viewMode: "wechat", body: "一份保险合同里，最容易被忽略的往往不是数字，而是数字成立的条件。读条款时，可以先从责任、限制和时间三个维度开始。" }],
  },
];
